language: node_js
node_js:
  - lts/*
install:
  - git checkout gh-pages
  - yarn install # npm ci
script:
  - yarn build # npm run build
  - cp CNAME dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: 5a315fe73182d8653f0a15d44c04e325475acff8 # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master